import java.io.*;
import java.net.*;
import java.nio.file.Path;
import java.util.*;

public class GetBg implements Runnable {
	private FtpClient ftpClient;
	private Socket socket;
	private Path serverPath, path;
	private String[] tokens;
	private int terminateID;

	private InputStreamReader iStream;
	private BufferedReader br;
	private DataInputStream byteStream;
	private OutputStream oStream;
	private DataOutputStream dStream;

	public GetBg(FtpClient ftpClient, String hostname, int nPort, String[] tokens, Path serverPath, Path path)
			throws Exception {
		this.ftpClient = ftpClient;
		this.tokens = tokens;
		this.serverPath = serverPath;
		this.path = path;

		InetAddress ip = InetAddress.getByName(hostname);
		socket = new Socket();
		socket.connect(new InetSocketAddress(ip.getHostAddress(), nPort), 1000);

		iStream = new InputStreamReader(socket.getInputStream());
		br = new BufferedReader(iStream);
		byteStream = new DataInputStream(socket.getInputStream());
		oStream = socket.getOutputStream();
		dStream = new DataOutputStream(oStream);
	}

	public void get() throws Exception {
		if (!ftpClient.transfer(serverPath.resolve(tokens[1]))) {
			//System.out.println("error: file already transfering");
			return;
		}

		dStream.writeBytes("get " + serverPath.resolve(tokens[1]) + "\n");

		String get_line;
		if (!(get_line = br.readLine()).equals("")) {
			System.out.println("empty get " + get_line);
			return;
		}

		try {
			terminateID = Integer.parseInt(br.readLine());// given by server
			System.out.println(terminateID);
		} catch (Exception e) {
			System.out.println(e);
		}
		System.out.println("Command ID: " + terminateID);

		// check here commandID entered is same as generated by server

		ftpClient.transferIN(serverPath.resolve(tokens[1]), terminateID);

		if (ftpClient.terminateGET(path.resolve(tokens[1]), serverPath.resolve(tokens[1]), terminateID))
			return;

		byte[] fileSizeBuffer = new byte[8];
		byteStream.read(fileSizeBuffer);
		ByteArrayInputStream bais = new ByteArrayInputStream(fileSizeBuffer);
		DataInputStream dis = new DataInputStream(bais);
		long fileSize = dis.readLong();

		if (ftpClient.terminateGET(path.resolve(tokens[1]), serverPath.resolve(tokens[1]), terminateID)) {
			// terminated = true;
			return;
		}

		FileOutputStream f = new FileOutputStream(new File(tokens[1]));
		int count, pcount = 0;
		byte[] buffer = new byte[8192];
		long bytesReceived = 0;

		while (bytesReceived < fileSize) {
			if (pcount > 1000) {
				pcount = 0;
				if (ftpClient.terminateGET(path.resolve(tokens[1]), serverPath.resolve(tokens[1]), terminateID)) {
					f.close();
					return;
				}
			}
			count = byteStream.read(buffer);
			pcount = count;
			f.write(buffer, 0, count);
			bytesReceived += count;
		}

		f.close();

		// CLIENT side un-locking
		ftpClient.transferOUT(serverPath.resolve(tokens[1]), terminateID);
	}

	public void run() {
		try {
			get();
			Thread.sleep(100);
			dStream.writeBytes("quit" + "\n");
		} catch (Exception e) {
			System.out.println(e);
		}
	}
}
